custom package.json
This reverts commit 982c621202a40400e95b26ce0c22fde32a0b4af6.

diff --git a/.github/workflows/check-spec.yml b/.github/workflows/check-spec.yml
--- a/.github/workflows/check-spec.yml
+++ b/.github/workflows/check-spec.yml
@@ -162,27 +162,42 @@ jobs:
           # zip the client
           zip -r clients/galv-client-python.zip clients/python
 
-      - name: Create ts-axios config
-        run: |
-          echo '{"npmName": "galv", "npmVersion": "${{ needs.version.outputs.version-plain }}"}' >> ts-config.json
-          cat ts-config.json
       - name: Create API client - typescript-axios
         env:
-          VERSION: ${{ needs.version.outputs.version }}
+          VERSION: ${{ needs.version.outputs.version-plain }}
         run: |
           JSON_FILE=$(ls .dev/spec/*.json)
           docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.6.0 generate \
           -i "/local/$JSON_FILE" \
           -g typescript-axios \
-          -c /local/ts-config.json \
           -o /local/clients/typescript-axios
           
           # Copy LICENCE file to client directory
           sudo cp LICENCE clients/typescript-axios/LICENCE
           
-          tree clients/typescript-axios
-          cat clients/typescript-axios/package.json
-          sudo chmod 777 clients/typescript-axios
+          # Create a package.json file using EOF notation
+          cat << EOF | sudo tee -a clients/typescript-axios/package.json
+          {
+              "name": "@battery-intelligence-lab/galv",
+              "version": "$VERSION",
+              "description": "Galv API client using Typescript-Axios",
+              "main": "index.ts",
+              "scripts": {
+                "test": "echo \"Error: no test specified\" && exit 1"
+              },
+              "keywords": [
+                "galv",
+                "galv-api",
+                "galv-client",
+                "typescript-axios"
+              ],
+              "author": "Battery Intelligence Lab",
+              "license": "See LICENCE File",
+              "dependencies": {
+                "axios": "^0.21.1"
+              }
+          }
+          EOF
           
           # zip the client
           zip -r clients/galv-client-typescript-axios.zip clients/typescript-axios
