fix: multi-job workflow
Called workflows must be jobs, not steps.

diff --git a/.github/workflows/configure-workflows.yml b/.github/workflows/configure-workflows.yml
--- a/.github/workflows/configure-workflows.yml
+++ b/.github/workflows/configure-workflows.yml
@@ -20,11 +20,26 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  get-version:
+  version:
     # Determine the version from the tag or branch name.
     # Determine the previous version from the tags.
     # Determine the previous major version from the tags.
     runs-on: ubuntu-latest
+    outputs:
+      API_VERSION: ${{ steps.current_version.outputs.API_VERSION }}
+      IS_TAG: ${{ steps.current_version.outputs.IS_TAG }}
+      REF_NAME: ${{ steps.current_version.outputs.REF_NAME }}
+      VERSION: ${{ steps.current_version.outputs.VERSION }}
+      VERSION_CLEAN: ${{ steps.current_version.outputs.VERSION_CLEAN }}
+      VERSION_SUFFIX: ${{ steps.current_version.outputs.VERSION_SUFFIX }}
+      IS_RELEASE: ${{ steps.current_version.outputs.IS_RELEASE }}
+      IS_STAGE: ${{ steps.current_version.outputs.IS_STAGE }}
+      PREVIOUS_VERSION: ${{ steps.previous_versions.outputs.PREVIOUS_VERSION }}
+      PREVIOUS_MAJOR_VERSION: ${{ steps.previous_versions.outputs.PREVIOUS_MAJOR_VERSION }}
+      IS_MAJOR_VERSION: ${{ steps.previous_versions.outputs.IS_MAJOR_VERSION }}
+      DOCS_CHANGED: ${{ steps.check_content_changes.outputs.DOCS_CHANGED }}
+      BACKEND_CHANGED: ${{ steps.check_content_changes.outputs.BACKEND_CHANGED }}
+      DEMO_UPDATE: ${{ steps.check_content_changes.outputs.DEMO_UPDATE }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -41,14 +56,14 @@ jobs:
               exit 1
           fi
 
-          echo "API_VERSION=v$API_VERSION" >> $GITHUB_ENV
+          echo "API_VERSION=v$API_VERSION" >> $GITHUB_OUTPUT
 
           if [[ "${{ github.ref_type }}" == "tag" ]]; then
                 IS_TAG=true
           else
                 IS_TAG=false
           fi
-          echo "IS_TAG=$IS_TAG" >> $GITHUB_ENV
+          echo "IS_TAG=$IS_TAG" >> $GITHUB_OUTPUT
 
           # Determine the tag/branch name
           if [[ $IS_TAG -gt 0 ]]; then
@@ -62,9 +77,9 @@ jobs:
           # Determine the version from the tag/branch name
           if ! [[ "$REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]]; then
               echo "Ref $REF_NAME is not valid semver. Using API_VERSION v$API_VERSION"
-              echo "VERSION=v$API_VERSION" >> $GITHUB_ENV
-              echo "VERSION_CLEAN=v$API_VERSION" >> $GITHUB_ENV
-              echo "VERSION_SUFFIX=" >> $GITHUB_ENV
+              echo "VERSION=v$API_VERSION" >> $GITHUB_OUTPUT
+              echo "VERSION_CLEAN=v$API_VERSION" >> $GITHUB_OUTPUT
+              echo "VERSION_SUFFIX=" >> $GITHUB_OUTPUT
           else
               VERSION_CLEAN=$(echo $REF_NAME | grep -oP '^v[0-9]+\.[0-9]+\.[0-9]+' || true)
               VERSION_SUFFIX=$(echo $REF_NAME | grep -oP '(?<=-).*$' || true)
@@ -76,23 +91,23 @@ jobs:
                   exit 1
               fi
 
-              echo "VERSION=$REF_NAME" >> $GITHUB_ENV
-              echo "VERSION_CLEAN=$VERSION_CLEAN" >> $GITHUB_ENV
-              echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV
+              echo "VERSION=$REF_NAME" >> $GITHUB_OUTPUT
+              echo "VERSION_CLEAN=$VERSION_CLEAN" >> $GITHUB_OUTPUT
+              echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_OUTPUT
           fi
 
           # Release versions are clean semver
-          echo "IS_RELEASE=$(($IS_TAG && "$REF_NAME" == "$VERSION_CLEAN"))" >> $GITHUB_ENV
+          echo "IS_RELEASE=$(($IS_TAG && "$REF_NAME" == "$VERSION_CLEAN"))" >> $GITHUB_OUTPUT
 
           # Ending in -rc# means it is a release candidate and should be staged
           if [[ "$REF_NAME" =~ \-rc[0-9]+$ ]]; then
-            echo "IS_STAGE=false" >> $GITHUB_ENV
+            echo "IS_STAGE=false" >> $GITHUB_OUTPUT
           else
-            echo "IS_STAGE=true" >> $GITHUB_ENV
+            echo "IS_STAGE=true" >> $GITHUB_OUTPUT
           fi
 
-          echo "Set env vars:"
-          cat $GITHUB_ENV
+          echo "Set output:"
+          cat $GITHUB_OUTPUT
 
       - name: Check version
         run: |
@@ -137,12 +152,12 @@ jobs:
           # PREVIOUS_MAJOR_VERSION
           # IS_LATEST
           if [[ "$PREVIOUS_VERSION" == "$PREVIOUS_MAJOR_VERSION" ]]; then
-            echo "IS_MAJOR_VERSION=true" >> $GITHUB_ENV
+            echo "IS_MAJOR_VERSION=true" >> $GITHUB_OUTPUT
           else
-            echo "IS_MAJOR_VERSION=false" >> $GITHUB_ENV
+            echo "IS_MAJOR_VERSION=false" >> $GITHUB_OUTPUT
           fi
-          echo "Set env vars:"
-          cat $GITHUB_ENV
+          echo "Set output:"
+          cat $GITHUB_OUTPUT
 
       - name: Check content changes
         id: check_content_changes
@@ -151,10 +166,10 @@ jobs:
           git diff --name-only $PREVIOUS_VERSION > diff.txt
           if [[ -z $(cat diff.txt | grep ^docs) ]]; then
               echo "No changes to docs directory"
-              echo "DOCS_CHANGED=false" >> $GITHUB_ENV
+              echo "DOCS_CHANGED=false" >> $GITHUB_OUTPUT
           else
               echo "Changes to docs directory detected"
-              echo "DOCS_CHANGED=true" >> $GITHUB_ENV
+              echo "DOCS_CHANGED=true" >> $GITHUB_OUTPUT
           fi
 
           # Check if `backend_django` directory has changed using git diff vs the previous version
@@ -162,28 +177,37 @@ jobs:
               if [[ -z $(cat diff.txt | grep -v -E '^(\.gitignore|\.pre-commit-config.yaml|LICENCE|README\.md)$' | grep -E ^[^/]+$) ]]; then
                   echo "No changes to settings_base.py or root directory files"
                   echo "(.gitignore, .pre-commit-config.yaml, LICENCE, README.md are ignored)"
-                  echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
+                  echo "BACKEND_CHANGED=false" >> $GITHUB_OUTPUT
               else
                   echo "Changes to root directory files detected"
                   echo "(.gitignore, .pre-commit-config.yaml, LICENCE, README.md are ignored)"
-                  echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
+                  echo "BACKEND_CHANGED=true" >> $GITHUB_OUTPUT
               fi
           else
               echo "Changes to backend_django directory detected"
-              echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
+              echo "BACKEND_CHANGED=true" >> $GITHUB_OUTPUT
           fi
 
           # Check if the demo instance workflow has been changed
           if [[ -z $(git diff $PREVIOUS_VERSION -- .github/workflows/demo.yml | grep DEMO_BACKEND_VERSION) ]]; then
               echo "No changes to DEMO_BACKEND_VERSION detected"
-              echo "DEMO_UPDATE=false" >> $GITHUB_ENV
+              echo "DEMO_UPDATE=false" >> $GITHUB_OUTPUT
           else
               echo "Changes to DEMO_BACKEND_VERSION detected"
-              echo "DEMO_UPDATE=true" >> $GITHUB_ENV
+              echo "DEMO_UPDATE=true" >> $GITHUB_OUTPUT
           fi
 
+
+  openapi-spec:
+    runs-on: ubuntu-latest
+    outputs:
+        API_CHANGES: ${{ steps.check_openapi_changes.outputs.API_CHANGES }}
+        BREAKING_API_CHANGES: ${{ steps.check_openapi_changes.outputs.BREAKING_API_CHANGES }}
+    needs:
+      - version
+    if: needs.version.outputs.BACKEND_CHANGED == 'true'
+    steps:
       - name: Setup docker-compose for OpenAPI spec check
-        if: env.BACKEND_CHANGED == 'true'
         run: |
           sudo apt-get update
           sudo apt-get install -y docker-compose
@@ -192,7 +216,7 @@ jobs:
           touch .env.secret
 
       - name: Check OpenAPI Spec changes
-        if: env.BACKEND_CHANGED == 'true'
+        if: needs.version.outputs.BACKEND_CHANGED == 'true'
         id: check_openapi_changes
         run: |
           # Generate the spec for this version
@@ -204,97 +228,112 @@ jobs:
             app \
             "python manage.py spectacular --fail-on-warn --validate --format openapi-json >> /spec/openapi-x.json"
           # Copy spec for upload
-          cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ env.VERSION_CLEAN }}.json
+          cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ needs.version.outputs.VERSION_CLEAN }}.json
 
           sudo chmod 777 .dev/spec/*
           # If previous version tag is empty, skip this step
-          if [ -z "${{ env.PREVIOUS_VERSION }}" ]; then
+          if [ -z "${{ needs.version.outputs.PREVIOUS_VERSION }}" ]; then
               echo "No previous version tag found. This is probably the first version. Skipping spec check."
               exit 0
           fi
-          wget -O .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json https://github.com/galv-team/galv-backend/releases/download/${{ needs.version.outputs.prev-clean-version }}/openapi-${{ needs.version.outputs.prev-clean-version }}.json || true
+          wget -O .dev/spec/openapi-${{ needs.version.outputs.PREVIOUS_VERSION }}.json https://github.com/galv-team/galv-backend/releases/download/${{ needs.version.outputs.prev-clean-version }}/openapi-${{ needs.version.outputs.prev-clean-version }}.json || true
           # Check whether we downloaded a file (i.e. whether that file has a size greater than 0)
-          if [ ! -s .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json ]; then
-              echo "Failed to download spec for previous version: ${{ env.PREVIOUS_VERSION }}."
+          if [ ! -s .dev/spec/openapi-${{ needs.version.outputs.PREVIOUS_VERSION }}.json ]; then
+              echo "Failed to download spec for previous version: ${{ needs.version.outputs.PREVIOUS_VERSION }}."
               echo "This can happen if something went wrong in publishing the previous version."
               echo "Generating spec from scratch..."
-              echo "Checking out previous version tag: ${{ env.PREVIOUS_VERSION }}"
+              echo "Checking out previous version tag: ${{ needs.version.outputs.PREVIOUS_VERSION }}"
               git fetch --tags
-              git checkout ${{ env.PREVIOUS_VERSION }}
-              echo "Generating spec for previous version: ${{ env.PREVIOUS_VERSION }}"
+              git checkout ${{ needs.version.outputs.PREVIOUS_VERSION }}
+              echo "Generating spec for previous version: ${{ needs.version.outputs.PREVIOUS_VERSION }}"
               docker-compose run --rm -e AWS_SECRET_ACCESS_KEY="not_set" --entrypoint "/bin/bash -c" app "python manage.py spectacular --format openapi-json >> /spec/openapi-x.json"
-              cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json
+              cp .dev/spec/openapi-x.json .dev/spec/openapi-${{ needs.version.outputs.PREVIOUS_VERSION }}.json
               echo "Success. Switching to workflow branch."
               git checkout -
               echo "Spec generated. First 10 lines:"
           else
-            echo "Downloaded spec for previous version: ${{ env.PREVIOUS_VERSION }}. First 10 lines:"
+            echo "Downloaded spec for previous version: ${{ needs.version.outputs.PREVIOUS_VERSION }}. First 10 lines:"
           fi
-          head -n 10 .dev/spec/openapi-${{ env.PREVIOUS_VERSION }}.json
+          head -n 10 .dev/spec/openapi-${{ needs.version.outputs.PREVIOUS_VERSION }}.json
           echo "---------"
-          echo "Check spec against previous version: ${{ env.PREVIOUS_VERSION }}"
-          if [[ "${{ env.IS_MAJOR_VERSION }}" == "true" || "${{ inputs.allow_breaking_changes }}" == "true" ]]; then
-            sudo docker-compose run --rm -e REMOTE_SPEC_SOURCE=/spec/openapi-${{ env.PREVIOUS_VERSION }}.json check_spec || true
+          echo "Check spec against previous version: ${{ needs.version.outputs.PREVIOUS_VERSION }}"
+          if [[ "${{ needs.version.outputs.IS_MAJOR_VERSION }}" == "true" || "${{ inputs.allow_breaking_changes }}" == "true" ]]; then
+            sudo docker-compose run --rm -e REMOTE_SPEC_SOURCE=/spec/openapi-${{ needs.version.outputs.PREVIOUS_VERSION }}.json check_spec || true
           else
-            sudo docker-compose run --rm -e REMOTE_SPEC_SOURCE=/spec/openapi-${{ env.PREVIOUS_VERSION }}.json check_spec
+            sudo docker-compose run --rm -e REMOTE_SPEC_SOURCE=/spec/openapi-${{ needs.version.outputs.PREVIOUS_VERSION }}.json check_spec
           fi
           ls -l .dev/spec
           echo ".dev/spec/diff.md:"
           cat .dev/spec/diff.md
           API_CHANGES=$(jq '.different' .dev/spec/diff.json)
           BREAKING_API_CHANGES=$(jq '.incompatible' .dev/spec/diff.json)
-          echo "API_CHANGES=$API_CHANGES" >> $GITHUB_ENV
-          echo "BREAKING_API_CHANGES=$BREAKING_API_CHANGES" >> $GITHUB_ENV
-          echo "Set env vars:"
-          cat $GITHUB_ENV
-
-      - name: Run tests
-        if: inputs.run_tests == 'true' || env.BACKEND_CHANGED == 'true'
-        uses: ./.github/workflows/ci-tests.yml
-
-      - name: Build and publish docs
-        if: env.DOCS_CHANGED == 'true'
-        uses: ./.github/workflows/docs.yml
-        with:
-          dry_run: ${{ !env.IS_RELEASE }}
+          echo "API_CHANGES=$API_CHANGES" >> $GITHUB_OUTPUT
+          echo "BREAKING_API_CHANGES=$BREAKING_API_CHANGES" >> $GITHUB_OUTPUT
+          echo "Set output:"
+          cat $GITHUB_OUTPUT
 
       - name: Upload OpenAPI spec
-        if: env.API_CHANGES == 'true'
+        if: steps.check_openapi_changes.outputs.API_CHANGES == 'true'
         uses: actions/upload-artifact@v4
         with:
           name: spec
-          path: .dev/spec/openapi-${{ env.VERSION_CLEAN }}.json
+          path: .dev/spec/openapi-${{ needs.version.outputs.VERSION_CLEAN }}.json
           retention-days: 1
 
       - name: Upload OpenAPI diff.md
-        if: env.API_CHANGES == 'true'
+        if: steps.check_openapi_changes.outputs.API_CHANGES == 'true'
         uses: actions/upload-artifact@v4
         with:
           name: diff
           path: .dev/spec/diff.md
           retention-days: 1
 
-      - name: Build and publish API clients
-        if: env.API_CHANGES == 'true'
-        uses: ./.github/workflows/api-clients.yml
-        with:
-          dry_run: ${{ env.IS_RELEASE == 'false' }}
-          base_version: ${{ env.VERSION_CLEAN }}
+  run_tests:
+    needs:
+      - version
+    if: needs.version.outputs.BACKEND_CHANGED == 'true' || needs.version.outputs.DOCS_CHANGED == 'true'
+    uses: ./.github/workflows/ci-tests.yml
 
-      - name: Build and publish Docker images
-        if: env.BACKEND_CHANGED == 'true'
-        uses: ./.github/workflows/docker-image.yml
-        with:
-          dry_run: ${{ env.IS_RELEASE == 'false' }}
+  docs:
+    needs:
+      - version
+    if: needs.version.outputs.DOCS_CHANGED == 'true'
+    uses: ./.github/workflows/docs.yml
+    with:
+      dry_run: ${{ needs.version.outputs.IS_RELEASE != 'true' }}
 
-      - name: Issue release
-        if: env.IS_RELEASE == 'true'
-        uses: ./.github/workflows/issue-release.yml
+  clients:
+    needs:
+      - version
+      - openapi-spec
+    if: needs.openapi-spec.outputs.API_CHANGES == 'true'
+    uses: ./.github/workflows/api-clients.yml
+    with:
+      dry_run: ${{ needs.version.outputs.IS_RELEASE == 'false' }}
+      base_version: ${{ needs.version.outputs.VERSION_CLEAN }}
 
-      - name: Update Staging instance
-        if: env.IS_STAGE == 'true'
-        uses: ./.github/workflows/update-staging.yml
+  docker:
+    needs:
+      - version
+    if: needs.version.outputs.BACKEND_CHANGED == 'true'
+    uses: ./.github/workflows/docker-image.yml
+    with:
+      dry_run: ${{ needs.version.outputs.IS_RELEASE == 'false' }}
 
-      - name: Update demo instance
-        if: env.DEMO_UPDATE == 'true'
-        uses: ./.github/workflows/update-demo.yml
+  release:
+    needs:
+      - version
+    if: needs.version.outputs.IS_RELEASE == 'true'
+    uses: ./.github/workflows/issue-release.yml
+
+  stage:
+    needs:
+      - version
+    if: needs.version.outputs.IS_STAGE == 'true'
+    uses: ./.github/workflows/update-staging.yml
+
+  demo:
+    needs:
+      - version
+    if: needs.version.outputs.DEMO_UPDATE == 'true'
+    uses: ./.github/workflows/update-demo.yml
