fix: nested workflows unsupported by pypi

diff --git a/.github/workflows/configure-workflows.yml b/.github/workflows/configure-workflows.yml
--- a/.github/workflows/configure-workflows.yml
+++ b/.github/workflows/configure-workflows.yml
@@ -16,6 +16,11 @@ on:
         description: 'Ignore breaking change failure in OpenAPI spec check.'
         required: false
         default: false
+      dry_run:
+        type: boolean
+        description: 'Do not actually release the package, just check that it is valid.'
+        required: false
+        default: false
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -367,13 +372,225 @@ jobs:
       - version
       - openapi-spec
       - tests
-    uses: ./.github/workflows/api-clients.yml
-    with:
-      skip: ${{ needs.openapi-spec.outputs.API_CHANGES != 'true' }}
-      dry_run: ${{ needs.version.outputs.IS_RELEASE != 'true' }}
-      version: ${{ needs.version.outputs.VERSION }}
-      version_clean: ${{ needs.version.outputs.VERSION_CLEAN }}
-    secrets: inherit
+    runs-on: ubuntu-latest
+    permissions:
+      packages: write
+      id-token: write  # IMPORTANT: mandatory for trusted publishing
+    environment:
+      name: ${{ needs.version.outputs.IS_RELEASE != 'true' && 'testpypi' || 'pypi' }}
+      url: ${{ needs.version.outputs.IS_RELEASE != 'true' && 'https://test.pypi.org/p/galv-client' || 'https://pypi.org/p/galv-client' }}
+    steps:
+      - uses: actions/checkout@v4
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+
+      - name: Make clients directory
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          mkdir clients
+
+      - name: Retrieve OpenAPI spec artifacts
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: actions/download-artifact@v4
+        with:
+          name: spec
+          path: .dev/spec
+
+      # Enable debugging of manually-triggered workflows if the input option was provided
+      - name: Debug
+        uses: owenthereal/action-upterm@v1
+        if: ${{ inputs.debug_enabled && needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+
+      - name: Login to Docker Hub
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: docker/login-action@v3
+        with:
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Specify openapi-generator version
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: docker pull openapitools/openapi-generator-cli:v6.6.0
+
+      - name: Determine Python package version
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          VERSION_CLEAN=${{ needs.version.outputs.VERSION_CLEAN }}
+          V=${VERSION_CLEAN#v}
+
+          # Real releases always use the clean tag version
+          if [[ "${{ needs.version.outputs.IS_RELEASE != 'true' }}" == "false" ]]; then
+            echo "PYPI_VERSION=$V" >> $GITHUB_ENV
+            exit 0
+          fi
+
+          # Get the list of currently published versions from the test repository
+          PYTHON_VERSIONS=$(pip index versions --pre --index-url https://test.pypi.org/simple/ galv)
+          while true; do
+            if ! echo "$PYTHON_VERSIONS" | grep -qE "$V(,|\s|$)"; then
+              break
+            fi
+
+            if [[ $V =~ dev[0-9]+$ ]]; then
+              V=$(echo "$V" | awk -F'dev' '{$NF = $NF + 1;} 1' | sed 's/ /dev/g')
+            else
+              V="${V}.dev0"
+            fi
+          done
+          echo "PYPI_VERSION=$V" >> $GITHUB_ENV
+
+      - name: Determine NPM package version
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          VERSION=${{ needs.version.outputs.VERSION }}
+          V=${VERSION#v}
+
+          # Real releases always use the clean tag version
+          if [[ "${{ needs.version.outputs.IS_RELEASE != 'true' }}" == "false" ]]; then
+              echo "NPM_VERSION=$V" >> $GITHUB_ENV
+              exit 0
+          fi
+
+          # Get the list of currently published versions
+          NPM_VERSIONS=$(npm show @galv/galv versions --json)
+
+          while true; do
+            if ! echo "$NPM_VERSIONS" | jq -e --arg v "$V" 'index($v)' > /dev/null; then
+              break
+            fi
+
+            if [[ $V =~ -?dev[0-9]+$ ]]; then
+              V=$(echo "$V" | awk -F'dev' '{$NF = $NF + 1;} 1' | sed 's/ /dev/')
+            else
+              V="${V}-dev0"
+            fi
+          done
+          echo "NPM_VERSION=$V" >> $GITHUB_ENV
+
+      - name: Create python config using calculated version
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          echo "{\"packageName\": \"galv\", \"packageVersion\": \"$PYPI_VERSION\"}" >> python-config.json
+          cat python-config.json
+
+      - name: Create API client - python
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          JSON_FILE=$(ls .dev/spec/*.json)
+          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.6.0 generate \
+          -i "/local/$JSON_FILE" \
+          -g python \
+          -c /local/python-config.json \
+          -o /local/clients/python
+
+          # Copy LICENCE file to client directory
+          sudo cp LICENCE clients/python/LICENCE
+
+          tree clients/python
+
+          # zip the client
+          zip -r clients/galv-client-python.zip clients/python
+
+      - name: Create API client - typescript-axios
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          # Create a config json file using EOF notation
+          echo '{"useSingleRequestParameter": true}' >> typescript-axios-config.json
+          JSON_FILE=$(ls .dev/spec/*.json)
+          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.6.0 generate \
+          -i "/local/$JSON_FILE" \
+          -g typescript-axios \
+          -c /local/typescript-axios-config.json \
+          -o /local/clients/typescript-axios
+
+          # Copy LICENCE file to client directory
+          sudo cp LICENCE clients/typescript-axios/LICENCE
+
+          # Create a package.json file using EOF notation
+          cat << EOF | sudo tee -a clients/typescript-axios/package.json
+          {
+              "name": "@galv/galv",
+              "version": "$NPM_VERSION",
+              "description": "Galv API client using Typescript-Axios",
+              "main": "index.ts",
+              "scripts": {
+                "test": "echo \"Error: no test specified\" && exit 1"
+              },
+              "keywords": [
+                "galv",
+                "galv-api",
+                "galv-client",
+                "typescript-axios"
+              ],
+              "author": "Battery Intelligence Lab",
+              "license": "See LICENCE File",
+              "dependencies": {
+                "axios": "^0.21.1"
+              }
+          }
+          EOF
+
+          # zip the client
+          zip -r clients/galv-client-typescript-axios.zip clients/typescript-axios
+
+      - name: Setup publishing typescript client to packages
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+
+      - name: Publish typescript client to packages ${{ needs.version.outputs.IS_RELEASE != 'true' && '[dry_run]' || '' }}
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: JS-DevTools/npm-publish@v3
+        with:
+          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
+          package: "clients/typescript-axios"
+          access: "public"
+          dry-run: ${{ needs.version.outputs.IS_RELEASE != 'true' }}
+
+      - name: Upload clients
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: clients
+          path: clients/*.zip
+          retention-days: 1
+
+      - name: Upload python client code
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: python
+          path: clients/python
+          retention-days: 1
+
+      - name: Build distribution 📦
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        run: |
+          ls -la clients/python
+          sudo chmod 777 clients/python
+          ls -la clients/python
+          cd clients/python
+          python setup.py sdist bdist_wheel
+          tree .
+
+      - name: Publish distribution 📦 to PyPI [dry_run]
+        if: ${{ needs.version.outputs.IS_RELEASE != 'true' && needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          repository-url: https://test.pypi.org/legacy/
+          packages-dir: clients/python/dist
+
+      - name: Publish distribution 📦 to PyPI
+        if: ${{ needs.version.outputs.IS_RELEASE == 'true' && needs.openapi-spec.outputs.API_CHANGES == 'true' }}
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          repository-url: https://upload.pypi.org/legacy/
+          packages-dir: clients/python/dist
+
+      - name: Rubber stamp
+        if: ${{ needs.openapi-spec.outputs.API_CHANGES != 'true' }}
+        run: |
+          echo "API clients not required because API hasn't changed."
 
   docker:
     needs:
